code --install-extension Arjun.swagger-viewer
code --install-extension austin.code-gnu-global
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension cmborchert.local-import-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension dbaeumer.vscode-eslint
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.code-runner
code --install-extension joelday.docthis
code --install-extension leizongmin.node-module-intellisense
code --install-extension lukas-tr.materialdesignicons-intellisense
code --install-extension mrmlnc.vscode-scss
code --install-extension ms-azuretools.vscode-azureappservice
code --install-extension ms-vscode.azure-account
code --install-extension ms-vscode.cpptools
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension OfHumanBondage.react-proptypes-intellisense
code --install-extension ritwickdey.LiveServer
code --install-extension sachinb94.document-tree
code --install-extension salesforce.salesforcedx-vscode-apex
code --install-extension salesforce.salesforcedx-vscode-apex-debugger
code --install-extension salesforce.salesforcedx-vscode-core
code --install-extension sburg.vscode-javascript-booster
code --install-extension trinm1709.dracula-theme-from-intellij
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension xabikos.JavaScriptSnippets
code --install-extension zh9528.file-size
code --install-extension Zignd.html-css-class-completion
