export const GET_ITEMS = "GET_ITEMS";
export const ADD_ITEM = "ADD_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const ITEMS_LOADING = "ITEMS_LOADING";

//USER
export const USER_LOADING = "USER_LOADING";
export const ALL_USERS_LOADED = "ALL_USERS_LOADED";
export const USER_LOADED = "USER_LOADED";
export const USER_DELETED = "USER_DELETED";

//AUTH
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

//ERRORS
export const AUTH_ERROR = "AUTH_ERROR";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

//GOOGLE 2FA
export const TFA_VERIFED = "TFA_VERIFED";
export const TFA_SETUP_SUCCESS = "TFA_SETUP_SUCCESS";
export const TFA_SETUP_FAIL = "TFA_SETUP_FAIL";
export const TFA_LOAD_FAIL = "TFA_LOAD_FAIL";
export const TFA_VERIFY_FAIL = "TFA_VERIFY_FAIL";
export const TFA_LOADED = "TFA_LOADED";
export const TFA_ING = "TFA_ING";
export const LOAD_SWAGGER_UI_ERROR = "LOAD_SWAGGER_UI_ERROR";
export const SWAGGER_UI_LOADED = "SWAGGER_UI_LOADED";
export const LOADING = "LOADING";

//ADMIN ACTIONS
export const DOWNLOAD_LOGGED = "DOWNLOAD_LOGGED";
export const LOGIN_LOGGED = "LOGIN_LOGGED";
export const ALL_LOGS_LOADED = "ALL_LOGS_LOADED";
export const LOAD_LOGS_ERROR = "LOAD_LOGS_ERROR";
